### ISSUE TITLE
Can't build jjd on OpenBSD

### ISSUE THREAD

**Issue by Veraellyunjie** [aaronNGi/jj#13]
```
make
cc -O2 -pipe  -pedantic -Wall -I. -I/usr/include -D_POSIX_C_SOURCE=200809L -D_POSIX_C_SOURCE=200809L -c jjd.c
CC -o jjd
cc -o jjd jjd.o -s -L/usr/lib -lc -lsocket
ld: error: unable to find library -lsocket
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in /tmp/jj (Makefile:21 'jjd')
```

`cc` is `clang` on OpenBSD

Utilizing `locate`, I see `/usr/include/sys/socket.h` present.

I also tried with `CC = egcc` in `Makefile` (egcc is gcc from repo to distinguish it from gcc from base),  
and `gmake`, same:
```
gmake
CC -o jjd
egcc -o jjd jjd.o -s -L/usr/lib -lc -lsocket
ld: error: unable to find library -lsocket
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:21: jjd] Error 1
```

**Comment by aaronNGi** [comment]
Sorry for the late response.

You can simply revert 409a41497bf2fcff08d555432a78598fca891fb4 and it should build just fine. At least it did for me just now on an OpenBSD box.

**Comment by Veraellyunjie** [comment]
I confirm that it builds, thank you

**Comment by aaronNGi** [comment]
> I confirm that it builds, thank you

Ok, good. Thank you for confirming.
